version: '3.8'
services:
  app:
    build: .
    ports:
      - '5000:5000' # Map host port 5000 to container port 5000
    environment:
      - MONGO_URI=mongodb://mongo:27017/android-manager-db
      - PORT=5000
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017' # Map host port 27017 to container port 27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
